import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar autogenerata dalla cartella docs/.
 * Le sub-cartelle (teoria/, scelte-tecniche/) sono trasformate in categorie
 * grazie ai relativi _category_.json file.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
